services:
  _defaults: { autowire: true, autoconfigure: true, public: false }
  LexprodSas\ContaoContentApiBundle\Controller\ContentApiController:
    public: true
    calls:
      - method: setContainer
        arguments: [ '@service_container' ]

parameters:
  content_api_enabled: true
  content_api_readers:
    newsreader: NewsModel
  content_api_modules:
    ModuleNewsList: ModuleNewsList
  content_api_headers:
    "Access-Control-Allow-Origin": "*"
